load("@rules_go//go:def.bzl", "go_binary", "go_library", "go_test")

package(default_visibility = ["//tf/private:__subpackages__"])

go_library(
    name = "runner_lib",
    srcs = ["main.go"],
    importpath = "github.com/benbirt/rules_tofu/tf/private/cmd/runner",
)

go_binary(
    name = "runner",
    embed = [":runner_lib"],
)

go_test(
    name = "runner_test",
    srcs = ["main_test.go"],
    args = ["-runner=$(rlocationpath :runner)"],
    data = [":runner"],
)
