# This target collects all of the parent workspace files needed by the broken_workspace child workspace.
filegroup(
    name = "local_repository_files",
    srcs = [
        "BUILD.bazel",
        "MODULE.bazel",
        "//terraform:all_files",
        "//terraform/private:all_files",
        "//terraform/private/cmd/dupcheck:all_files",
        "//toolchain:all_files",
    ],
    visibility = ["//:__subpackages__"],
)

