"""Internal fmt rules used by the `tf_library` and `tf_deploy` macros.

Not part of the public API (`//tf:defs.bzl`). Use the `fmt_test`
parameter on `tf_library` or `tf_deploy` instead.
"""

load("//toolchain:toolchain.bzl", "TOOLCHAIN_TYPE")

def _runfiles_path(workspace_name, f):
    sp = f.short_path
    if sp.startswith("../"):
        return sp[3:]
    return workspace_name + "/" + sp

def _tf_fmt_impl(ctx):
    tofu = ctx.toolchains[TOOLCHAIN_TYPE].tofu
    workspace_name = ctx.workspace_name or "_main"
    tofu_rel = _runfiles_path(workspace_name, tofu.binary)

    out = ctx.actions.declare_file(ctx.label.name + ".sh")
    ctx.actions.write(
        output = out,
        is_executable = True,
        content = """\
#!/usr/bin/env bash
# Generated by rules_tofu's tf_fmt macro. Do not edit.
set -euo pipefail
R="${{0}}.runfiles"
"$R/{tofu}" fmt "${{BUILD_WORKSPACE_DIRECTORY:?must be invoked via 'bazel run'}}/{pkg}"
""".format(tofu = tofu_rel, pkg = ctx.label.package),
    )

    return [DefaultInfo(
        executable = out,
        runfiles = ctx.runfiles(files = [tofu.binary]),
    )]

tf_fmt = rule(
    implementation = _tf_fmt_impl,
    executable = True,
    toolchains = [TOOLCHAIN_TYPE],
)

def _tf_fmt_check_impl(ctx):
    tofu = ctx.toolchains[TOOLCHAIN_TYPE].tofu
    workspace_name = ctx.workspace_name or "_main"
    tofu_rel = _runfiles_path(workspace_name, tofu.binary)

    out = ctx.actions.declare_file(ctx.label.name + ".sh")
    ctx.actions.write(
        output = out,
        is_executable = True,
        content = """\
#!/usr/bin/env bash
# Generated by rules_tofu's tf_fmt macro. Do not edit.
set -euo pipefail
R="${{TEST_SRCDIR:?must be run as a Bazel test}}"
"$R/{tofu}" fmt -check "$R/{workspace}/{pkg}"
""".format(tofu = tofu_rel, workspace = workspace_name, pkg = ctx.label.package),
    )

    return [DefaultInfo(
        executable = out,
        runfiles = ctx.runfiles(files = [tofu.binary] + ctx.files.srcs),
    )]

tf_fmt_check_test = rule(
    implementation = _tf_fmt_check_impl,
    test = True,
    attrs = {
        "srcs": attr.label_list(
            allow_files = [".tf", ".tf.json"],
            doc = "Source files to check; included as runfiles so the test sees them.",
        ),
    },
    toolchains = [TOOLCHAIN_TYPE],
)

