"""Providers exchanged between rules_tofu rules.

These providers are the typed channel by which the dep graph composes:
the `tf_library` rule emits a `TfLibraryInfo` carrying its
own files plus its transitive deps' files; downstream libraries and the
root `tf_deploy` consume it to assemble the full input set, and
the runner rule reads `TfDeployInfo` for the deploy's runfiles set,
its package directory, var-file paths, and plugin-dir relpath — the
inputs it needs to invoke `tofu` against the materialized work tree.
"""

visibility(["public"])

# Carried by a `tf_provider` target generated by the
# `@rules_tofu//tf/providers:extensions.bzl` extension. The deploy rule
# picks `binaries[exec_platform_key]` and symlinks it into the work tree's
# plugin dir at the canonical
# `<host>/<namespace>/<name>/<version>/<os>_<arch>/<filename>` path.
TfProviderInfo = provider(
    doc = "A vendored OpenTofu/Terraform provider plugin binary, per platform.",
    fields = {
        "address": "string: the canonical provider address, e.g. \"registry.opentofu.org/hashicorp/aws\".",
        "version": "string: the provider version, e.g. \"5.70.0\".",
        "binaries": "dict[string -> File]: provider binary keyed by `<os>_<arch>` platform key.",
    },
)

# An entry in `transitive_files` is a `struct(path, file)`, where `path` is
# the workspace-relative path at which the file should appear in the
# materialized working tree.
TfLibraryInfo = provider(
    doc = "Carries the .tf and data files contributed by a tf_library and all its transitive library deps.",
    fields = {
        "transitive_files": "depset[struct(path, file)] of .tf and arbitrary data files across the dep graph.",
        "providers": "depset[TfProviderInfo]: providers contributed by this library and its transitive deps.",
    },
)

# The materialized work tree is a directory output of `_tf_deploy`
# rooted at `bazel-bin/<package>/<name>.work/`. Every transitive .tf file
# (plus the generated rules_tofu.auto.tfvars.json) appears under that root
# at its workspace-relative path.
TfDeployInfo = provider(
    doc = "Carries everything a runner needs to execute `tofu` against a root deploy.",
    fields = {
        "work_tree_files": "depset[File]: every file inside the work tree (so runfiles include them).",
        "package_dir": "string: workspace-relative directory the runner cd's into before running tofu.",
        "var_file_relpaths": "list[string]: workspace-relative paths of -var-file inputs, in declaration order.",
        "plugin_dir_relpath": "string: work-tree-root-relative path to the vendored plugin tree. " +
                              "The runner joins it with the runfiles work tree root to form `-plugin-dir=...`.",
    },
)
