"""`terraform_fmt` macro.

The macro emits:
  - `:<name>`       — runnable: `bazel run :<name>` rewrites all .tf files in
                      the package directory to canonical OpenTofu style.
  - `:<name>_check` — test: `bazel test :<name>_check` fails if any .tf file
                      in the package directory is not already formatted.
                      Omitted when `check = False`.
"""

load("//toolchain:toolchain.bzl", "TOOLCHAIN_TYPE")

def _runfiles_path(workspace_name, f):
    sp = f.short_path
    if sp.startswith("../"):
        return sp[3:]
    return workspace_name + "/" + sp

def _tf_fmt_impl(ctx):
    tofu = ctx.toolchains[TOOLCHAIN_TYPE].tofu
    workspace_name = ctx.workspace_name or "_main"
    tofu_rel = _runfiles_path(workspace_name, tofu.binary)

    out = ctx.actions.declare_file(ctx.label.name + ".sh")
    ctx.actions.write(
        output = out,
        is_executable = True,
        content = """\
#!/usr/bin/env bash
# Generated by terrazel's terraform_fmt macro. Do not edit.
set -euo pipefail
R="${{0}}.runfiles"
"$R/{tofu}" fmt "${{BUILD_WORKSPACE_DIRECTORY:?must be invoked via 'bazel run'}}/{pkg}"
""".format(tofu = tofu_rel, pkg = ctx.label.package),
    )

    return [DefaultInfo(
        executable = out,
        runfiles = ctx.runfiles(files = [tofu.binary]),
    )]

_tf_fmt = rule(
    implementation = _tf_fmt_impl,
    executable = True,
    toolchains = [TOOLCHAIN_TYPE],
)

def _tf_fmt_check_impl(ctx):
    tofu = ctx.toolchains[TOOLCHAIN_TYPE].tofu
    workspace_name = ctx.workspace_name or "_main"
    tofu_rel = _runfiles_path(workspace_name, tofu.binary)

    out = ctx.actions.declare_file(ctx.label.name + ".sh")
    ctx.actions.write(
        output = out,
        is_executable = True,
        content = """\
#!/usr/bin/env bash
# Generated by terrazel's terraform_fmt macro. Do not edit.
set -euo pipefail
R="${{0}}.runfiles"
"$R/{tofu}" fmt -check "$R/{workspace}/{pkg}"
""".format(tofu = tofu_rel, workspace = workspace_name, pkg = ctx.label.package),
    )

    return [DefaultInfo(
        executable = out,
        runfiles = ctx.runfiles(files = [tofu.binary] + ctx.files.srcs),
    )]

_tf_fmt_check = rule(
    implementation = _tf_fmt_check_impl,
    test = True,
    attrs = {
        "srcs": attr.label_list(
            allow_files = [".tf", ".tf.json"],
            doc = "Source files to check; included as runfiles so the test sees them.",
        ),
    },
    toolchains = [TOOLCHAIN_TYPE],
)

def terraform_fmt(name, srcs = None, check = True, **kwargs):
    """Format all .tf files in the current package directory.

    Generates:
      - `:<name>`       — `bazel run` to reformat .tf files in-place.
      - `:<name>_check` — `bazel test` that fails if files are not already
                          formatted (omitted when `check = False`).

    Args:
      name: target name for the format runner.
      srcs: .tf source files for the check test's runfiles (typically
            `glob(["*.tf"])`). Ignored when `check = False`.
      check: whether to also emit a `:<name>_check` test target (default True).
      **kwargs: forwarded to both targets (visibility, tags, testonly).
    """
    _tf_fmt(name = name, **kwargs)

    if check:
        _tf_fmt_check(
            name = name + "_check",
            srcs = srcs or [],
            **kwargs
        )
