"""`tf_runner` rule.

Emits an executable that runs `tofu init && tofu <plan|apply>` against a
deploy's materialized work tree. The executable is a tiny shell wrapper
(~10 lines) that exec's the Go runner binary with all configuration
passed as explicit CLI flags — no template substitutions inside the
runner itself, no runfiles boilerplate in bash.
"""

load(":providers.bzl", "TerraformDeployInfo")
load("//toolchain:toolchain.bzl", "TOOLCHAIN_TYPE")

_RUNNER_BIN_LABEL = "//terraform/private/cmd/runner:runner"

def _runfiles_path(workspace_name, f):
    """Return the path at which `f` appears in a runfiles tree.

    Convention:
      - Main-repo files: `<workspace_name>/<short_path>`.
      - External-repo files: `<short_path>` with the leading `../` stripped.
    """
    sp = f.short_path
    if sp.startswith("../"):
        return sp[3:]
    return workspace_name + "/" + sp

def _tf_runner_impl(ctx):
    deploy = ctx.attr.deploy[TerraformDeployInfo]
    tofu = ctx.toolchains[TOOLCHAIN_TYPE].tofu
    runner_bin = ctx.attr._runner_bin[DefaultInfo].files_to_run.executable
    workspace_name = ctx.workspace_name or "_main"

    runner_rel = _runfiles_path(workspace_name, runner_bin)
    tofu_rel = _runfiles_path(workspace_name, tofu.binary)
    work_tree_rel = _runfiles_path(workspace_name, deploy.work_tree)

    # The work tree root is the dirname of the first materialized file
    # walked up to the `<name>.work/` segment. Computing that in shell
    # is fragile; instead we bake the work-tree root path directly.
    # The deploy rule materializes outputs at
    # `bazel-bin/<pkg>/<name>.work/<workspace-relative-path>`, so the
    # runfiles path of any of them starts with
    # `<workspace>/<pkg>/<name>.work/`. We compute that root here.
    work_tree_root = "{ws}/{pkg}/{name}.work".format(
        ws = workspace_name,
        pkg = ctx.attr.deploy.label.package,
        name = ctx.attr.deploy.label.name,
    )

    out = ctx.actions.declare_file(ctx.label.name + ".sh")
    ctx.actions.write(
        output = out,
        is_executable = True,
        content = """\
#!/usr/bin/env bash
# Generated by terrazel's tf_runner rule. Do not edit.
set -euo pipefail
R="${{0}}.runfiles"
exec "$R/{runner}" \\
    --tofu="$R/{tofu}" \\
    --work-tree="$R/{work_tree}" \\
    --package-dir="{pkg}" \\
    --state-id="{state_id}" \\
    --command="{command}" \\
    "$@"
""".format(
            runner = runner_rel,
            tofu = tofu_rel,
            work_tree = work_tree_root,
            pkg = deploy.package_dir,
            state_id = deploy.state_id,
            command = ctx.attr.command,
        ),
    )

    runfiles = ctx.runfiles(
        files = [tofu.binary] + deploy.work_tree_files.to_list(),
    ).merge(ctx.attr._runner_bin[DefaultInfo].default_runfiles)

    return [DefaultInfo(executable = out, runfiles = runfiles)]

tf_runner = rule(
    implementation = _tf_runner_impl,
    executable = True,
    attrs = {
        "deploy": attr.label(
            mandatory = True,
            providers = [TerraformDeployInfo],
        ),
        "command": attr.string(
            mandatory = True,
            values = ["plan", "apply"],
        ),
        "_runner_bin": attr.label(
            default = _RUNNER_BIN_LABEL,
            executable = True,
            cfg = "exec",
        ),
    },
    toolchains = [TOOLCHAIN_TYPE],
)
