"""`tf_runner` rule.

Emits an executable that runs `tofu init && tofu <plan|apply>` against a
deploy's materialized work tree. The executable is a tiny shell wrapper
(~10 lines) that exec's the Go runner binary with all configuration
passed as explicit CLI flags — no template substitutions inside the
runner itself, no runfiles boilerplate in bash.
"""

load(":providers.bzl", "TerraformDeployInfo")
load("//toolchain:toolchain.bzl", "TOOLCHAIN_TYPE")

_RUNNER_BIN_LABEL = "//terraform/private/cmd/runner:runner"

def _runfiles_path(workspace_name, f):
    """Return the path at which `f` appears in a runfiles tree.

    Convention:
      - Main-repo files: `<workspace_name>/<short_path>`.
      - External-repo files: `<short_path>` with the leading `../` stripped.
    """
    sp = f.short_path
    if sp.startswith("../"):
        return sp[3:]
    return workspace_name + "/" + sp

def _tf_runner_impl(ctx):
    deploy = ctx.attr.deploy[TerraformDeployInfo]
    tofu = ctx.toolchains[TOOLCHAIN_TYPE].tofu
    runner_bin = ctx.attr._runner_bin[DefaultInfo].files_to_run.executable
    workspace_name = ctx.workspace_name or "_main"

    runner_rel = _runfiles_path(workspace_name, runner_bin)
    tofu_rel = _runfiles_path(workspace_name, tofu.binary)
    work_tree_rel = _runfiles_path(workspace_name, deploy.work_tree)

    # The work tree root in runfiles is `<workspace>/<pkg>/<name>.work`,
    # because the deploy's outputs are declared at
    # `<pkg>/<name>.work/<workspace-relative-path>`.
    work_tree_root = "{ws}/{pkg}/{name}.work".format(
        ws = workspace_name,
        pkg = ctx.attr.deploy.label.package,
        name = ctx.attr.deploy.label.name,
    )

    # State lives at the deploy's `$(RULEDIR)/<name>.terrazel-state` —
    # i.e. `bazel-out/<config>/bin/<pkg>/<name>.terrazel-state`. That
    # path is already covered by the standard `bazel-*` gitignore and is
    # wiped by `bazel clean`. Bake the relative path here; the launcher
    # joins it with `$BUILD_WORKSPACE_DIRECTORY` at runtime.
    state_dir_rel = "{bin}/{pkg}/{name}.terrazel-state".format(
        bin = ctx.bin_dir.path,
        pkg = ctx.attr.deploy.label.package,
        name = ctx.attr.deploy.label.name,
    )

    var_file_flags = "".join([
        '    --var-file="$R/{root}/{p}" \\\n'.format(root = work_tree_root, p = p)
        for p in deploy.var_file_relpaths
    ])

    out = ctx.actions.declare_file(ctx.label.name + ".sh")
    ctx.actions.write(
        output = out,
        is_executable = True,
        content = """\
#!/usr/bin/env bash
# Generated by terrazel's tf_runner rule. Do not edit.
set -euo pipefail
R="${{0}}.runfiles"
exec "$R/{runner}" \\
    --tofu="$R/{tofu}" \\
    --work-tree="$R/{work_tree}" \\
    --package-dir="{pkg}" \\
    --state-dir="${{BUILD_WORKSPACE_DIRECTORY:?must be invoked via 'bazel run'}}/{state_dir_rel}" \\
    --command="{command}" \\
{var_file_flags}    -- "$@"
""".format(
            runner = runner_rel,
            tofu = tofu_rel,
            work_tree = work_tree_root,
            pkg = deploy.package_dir,
            state_dir_rel = state_dir_rel,
            command = ctx.attr.command,
            var_file_flags = var_file_flags,
        ),
    )

    runfiles = ctx.runfiles(
        files = [tofu.binary] + deploy.work_tree_files.to_list(),
    ).merge(ctx.attr._runner_bin[DefaultInfo].default_runfiles)

    return [DefaultInfo(executable = out, runfiles = runfiles)]

tf_runner = rule(
    implementation = _tf_runner_impl,
    executable = True,
    attrs = {
        "deploy": attr.label(
            mandatory = True,
            providers = [TerraformDeployInfo],
        ),
        "command": attr.string(
            mandatory = True,
            values = ["plan", "apply", "destroy"],
        ),
        "_runner_bin": attr.label(
            default = _RUNNER_BIN_LABEL,
            executable = True,
            cfg = "exec",
        ),
    },
    toolchains = [TOOLCHAIN_TYPE],
)
