load("@rules_tofu//tf:defs.bzl", "tf_deploy", "tf_library")

# Passing a file named `rules_tofu.auto.tfvars.json` in data must fail during materialization
# of the work tree because the rule itself generates a file at that same path from `vars`.
tf_library(
    name = "lib",
    srcs = ["main.tf"],
    data = ["rules_tofu.auto.tfvars.json"],
    fmt_test = False,
)

tf_deploy(
    name = "deploy",
    fmt_test = False,
    vars = {"foo": "bar"},
    deps = [":lib"],
)
