load("@rules_go//go:def.bzl", "go_binary", "go_library", "go_test")

package(default_visibility = ["//tf/private:__subpackages__"])

go_library(
    name = "dupcheck_lib",
    srcs = ["main.go"],
    importpath = "github.com/benbirt/rules_tofu/tf/private/cmd/dupcheck",
    deps = ["@com_github_hashicorp_hcl_v2//hclparse"],
)

go_binary(
    name = "dupcheck",
    embed = [":dupcheck_lib"],
)

go_test(
    name = "dupcheck_test",
    srcs = ["main_test.go"],
    args = ["-dupcheck=$(rlocationpath :dupcheck)"],
    data = [":dupcheck"],
)

filegroup(
    name = "all_files",
    srcs = glob(["*"]),
    visibility = ["//:__subpackages__"],
)
