#!/usr/bin/env bash
#
# Generated by terrazel's _tf_runner rule.
#
# Materializes the deploy's transitive .tf inputs into a scratch working tree,
# preserving workspace-relative paths, then invokes `tofu init` followed by
# `tofu <command>` from the deploy's package directory.

# --- begin runfiles.bash initialization v3 ---
# Canonical bash runfiles initialization. See:
# https://github.com/bazelbuild/bazel/blob/master/tools/bash/runfiles/runfiles.bash
set -uo pipefail; f=bazel_tools/tools/bash/runfiles/runfiles.bash
# shellcheck disable=SC1090
source "${RUNFILES_DIR:-/dev/null}/$f" 2>/dev/null || \
  source "$(grep -sm1 "^$f " "${RUNFILES_MANIFEST_FILE:-/dev/null}" | cut -f2- -d' ')" 2>/dev/null || \
  source "$0.runfiles/$f" 2>/dev/null || \
  source "$(grep -sm1 "^$f " "$0.runfiles/MANIFEST" | cut -f2- -d' ')" 2>/dev/null || \
  source "$(grep -sm1 "^$f " "$0.exe.runfiles/MANIFEST" | cut -f2- -d' ')" 2>/dev/null || \
  { echo>&2 "ERROR: cannot find $f"; exit 1; }; f=; set -e
# --- end runfiles.bash initialization v3 ---

COMMAND="%{command}%"
PACKAGE_DIR="%{package_dir}%"
TOFU_RLOCATION="%{tofu_rlocation}%"
LABEL_ID="%{label_id}%"

if [[ -z "${BUILD_WORKSPACE_DIRECTORY:-}" ]]; then
  echo >&2 "ERROR: terrazel runner must be invoked via \`bazel run\`."
  echo >&2 "       BUILD_WORKSPACE_DIRECTORY is unset, so state cannot be"
  echo >&2 "       persisted — refusing to operate against a transient temp dir."
  exit 1
fi

TOFU="$(rlocation "$TOFU_RLOCATION")"
if [[ -z "$TOFU" || ! -x "$TOFU" ]]; then
  echo >&2 "ERROR: failed to locate the tofu binary in runfiles (key=$TOFU_RLOCATION)."
  exit 1
fi

TERRAZEL_HOME="$BUILD_WORKSPACE_DIRECTORY/.terrazel"
STATE_DIR="$TERRAZEL_HOME/state/$LABEL_ID"
LOCK_DIR="$TERRAZEL_HOME/locks"
PLUGIN_CACHE_DIR="$TERRAZEL_HOME/plugin-cache"
mkdir -p "$STATE_DIR" "$LOCK_DIR" "$PLUGIN_CACHE_DIR"

export TF_PLUGIN_CACHE_DIR="$PLUGIN_CACHE_DIR"
export TF_IN_AUTOMATION=1
export TF_INPUT=0
# Permit cache reuse without strict lockfile hash matching. Once we adopt
# first-class .terraform.lock.hcl handling, drop this.
export TF_PLUGIN_CACHE_MAY_BREAK_DEPENDENCY_LOCK_FILE=1

# --- Stage a scratch working tree with workspace-relative paths -------------

WORK_DIR="$(mktemp -d -t terrazel.XXXXXX)"
cleanup() { rm -rf "$WORK_DIR"; }
trap cleanup EXIT

# The FILE_TABLE below is a newline-separated list of <rel_path>\t<rlocation_key>
# pairs, baked in by the _tf_runner rule at analysis time.
FILE_TABLE=$(cat <<'__TERRAZEL_FILE_TABLE__'
%{file_table}%
__TERRAZEL_FILE_TABLE__
)

while IFS=$'\t' read -r rel_path rloc_key; do
  [[ -z "$rel_path" ]] && continue
  src="$(rlocation "$rloc_key")"
  if [[ -z "$src" ]]; then
    echo >&2 "ERROR: failed to resolve runfile for $rel_path (key=$rloc_key)"
    exit 1
  fi
  dest="$WORK_DIR/$rel_path"
  mkdir -p "$(dirname "$dest")"
  # Prefer symlinks; fall back to copy for filesystems / cmds that lack ln -s.
  ln -s "$src" "$dest" 2>/dev/null || cp -f "$src" "$dest"
done <<<"$FILE_TABLE"

cd "$WORK_DIR/$PACKAGE_DIR"

# --- Serialize concurrent invocations against the same target ---------------

LOCK_FILE="$LOCK_DIR/$LABEL_ID.lock"
exec {LOCK_FD}>"$LOCK_FILE"
flock -x "$LOCK_FD"

# --- tofu init (always) -----------------------------------------------------

"$TOFU" init -input=false

# --- tofu plan / apply ------------------------------------------------------

PLAN_FILE="$STATE_DIR/tfplan"
STATE_FILE="$STATE_DIR/terraform.tfstate"

# If a backend block is declared in the merged config, OpenTofu uses it.
# Otherwise we point at our per-target state file so successive runs see the
# same state instead of starting fresh each time.
HAS_BACKEND=0
if grep -RnoE '^\s*backend\s+"' --include='*.tf' . >/dev/null 2>&1; then
  HAS_BACKEND=1
fi

state_args=()
if [[ $HAS_BACKEND -eq 0 ]]; then
  state_args=(-state="$STATE_FILE" -state-out="$STATE_FILE")
fi

case "$COMMAND" in
  plan)
    "$TOFU" plan -input=false -out="$PLAN_FILE" "${state_args[@]}" "$@"
    echo "terrazel: plan saved to $PLAN_FILE"
    ;;
  apply)
    # Always re-plan so apply consumes a fresh plan artifact rather than a
    # potentially-stale one.
    "$TOFU" plan -input=false -out="$PLAN_FILE" "${state_args[@]}"
    "$TOFU" apply -input=false "${state_args[@]}" "$PLAN_FILE"
    ;;
  *)
    echo >&2 "ERROR: unknown terrazel command: $COMMAND"
    exit 2
    ;;
esac
